import { createElement } from '@lwc/engine-dom';
import EventViewOfflineV2ActionWrapperoffline from 'c/eventViewOfflineV2ActionWrapperoffline';

describe('c-event-view-offline-v-2-action-wrapperoffline', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-event-view-offline-v-2-action-wrapperoffline', {
            is: EventViewOfflineV2ActionWrapperoffline
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});